apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: deploys.helm.k8s.ir
spec:
  group: helm.k8s.ir
  scope: Namespaced
  names:
    plural: deploys
    singular: deploy
    kind: DeployChart
    shortNames:
      - deploy
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                chart:
                  type: object
                  required:
                    - repo
                    - chart
                    - version
                  properties:
                    repo:
                      type: string
                    chart:
                      type: string
                    version:
                      type: string
                values:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
            status:
              type: object
              properties:
                processed:
                  type: boolean
                state:
                  type: string
                  enum: ["Pending", "Deploying", "Succeeded", "Failed"]
                message:
                  type: string
                lastAppliedHash:
                  type: string
      additionalPrinterColumns:
        - name: namespace
          type: string
          jsonPath: .metadata.namespace
        - name: Chart
          type: string
          jsonPath: .spec.chart.chart
        - name: Repo
          type: string
          jsonPath: .spec.chart.repo
        - name: Version
          type: string
          jsonPath: .spec.chart.version
        - name: Processed
          type: boolean
          jsonPath: .status.processed
        - name: State
          type: string
          jsonPath: .status.state
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp
        - name: Message
          type: string
          jsonPath: .status.message
      subresources:
        status: {}
