apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  # Must be <plural>.<group>
  name: repositories.helm.k8s.ir
spec:
  group: helm.k8s.ir
  scope: Cluster # namespaced or cluster based on your usage
  names:
    plural: repositories
    singular: repository
    kind: Repository
    shortNames:
      - repo
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                url:
                  type: string
                hasCredentials:
                  type: boolean
                  default: false
                username:
                  type: string
                  default: ""
                password:
                  type: string
                  default: ""
            status:
              type: object
              properties:
                processed:
                  type: boolean
      subresources:
        status: {}
      additionalPrinterColumns:
        - name: URL
          type: string
          jsonPath: .spec.url
        - name: Name
          type: string
          jsonPath: .metadata.name
        - name: Has Credentials
          type: string   # printer columns can't be boolean, so we use string
          jsonPath: .spec.hasCredentials
        - name: Processed
          type: string   # printer columns can't be boolean, so we use string
          jsonPath: .status.processed
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp
