apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: helm-operator-identity
  labels:
    app.kubernetes.io/name: helm-operator
  annotations:
    cert-manager.io/inject-ca-from: helm-operator/helm-operator-webhook-cert
webhooks:
  - name: deploychart-identity.helm.k8s.ir
    admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: helm-operator-webhook
        namespace: helm-operator
        path: /mutate-helm-k8s-ir-v1alpha1-deploychart-identity
        port: 443
    failurePolicy: Fail
    matchPolicy: Equivalent
    reinvocationPolicy: Never
    rules:
      - apiGroups:
          - helm.k8s.ir
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - deploys
        scope: Namespaced
    sideEffects: None
    timeoutSeconds: 10
