apiVersion: v1
kind: Service
metadata:
  name: helm-operator-webhook
  namespace: helm-operator
  labels:
    app.kubernetes.io/name: helm-operator
spec:
  selector:
    app.kubernetes.io/name: helm-operator
  ports:
    - name: https
      port: 443
      targetPort: webhook
      protocol: TCP
