apiVersion: v1
kind: Namespace
metadata:
  name: helm-operator
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: helm-operator-service-account
  namespace: helm-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: myapp-sa-cluster-admin
subjects:
  - kind: ServiceAccount
    name: helm-operator-service-account
    namespace: helm-operator
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: helm-operator-deployment
    namespace: helm-operator
spec:
  replicas: 2
  selector:
      matchLabels:
        app: helm-operator
  template:
    metadata:
      labels:
        app: helm-operator
    spec:
      serviceAccountName: helm-operator-service-account
      containers:
        - name: helm-operator
          image: ghcr.io/devazizi/helm-operator:v1.0.3
          imagePullPolicy: Always
