# A Secret named star-example-com must already exist in cert-manager. For
# example, it may be a TLS Secret maintained by cert-manager.
apiVersion: others.helm.k8s.ir/v1alpha1
kind: Reflector
metadata:
  name: star-example-com
  namespace: cert-manager
spec:
  kind: Secret
  reflectTo:
    - dev-*
    - prod-*
